### ISSUE TITLE
Why I use callback method to call C# functions still freezes UI?

### ISSUE THREAD

**Issue by kingeaglewang** [agracio/electron-edge-js#30] opened 2018-10-18 05:16 UTC
```
var TurnPasswordOn = edgejs.func({
    assemblyFile: XXX.dll',
    typeName: 'ABCDEFG',
    methodName: "TurnPasswordOn"
});

TurnPasswordOn(TurnPasswordOnInfo, function(err, ret){
                    if(err)
                    {
                        throw err;
                    }
                    if(ret == true)
                    {
                        alert("Set password success");
                    }
                    else
                    {
                        alert("Set password fail");
                    }
 });
```
Because the TurnPasswordOn function needs to take about 30~40 seconds, I want to do a loader animation.

But when the code executes to TurnPasswordOn function, it freezes the UI.
The loader animation is frozen (not going).
I'm just curious why I use callback function, but it still freezes the UI?

Thanks for helping.

**Comment by agracio** [comment] 2018-10-18 10:32
You need to handle `TurnPasswordOn` function properly in UI for it not to freeze. I would suggest using a promise.

**Comment by kingeaglewang** [comment] 2018-10-19 09:47
Did you mean I need to modify the code in C# side ?

**Comment by agracio** [comment] 2018-10-22 14:04
You need to handle JS `TurnPasswordOn` function. Warp it into a Promise or `async/await` statement.

**Comment by kingeaglewang** [comment] 2018-12-14 07:44
Yes. 
Same as your issue.
I use promise, but it still freezes the UI.

**Comment by agracio** [comment] 2018-12-26 14:17
After some research It appears that for async calls to work native module itself needs to support async calls. The problem is with Edge.js C++ code rather than JS async usage, and unfortunately there will be no resolution to this problem in foreseeable future.

**Comment by fabianosandi** [comment] 2020-03-10 13:03
I'm facing the same problem, is this still pending?

**Comment by agracio** [comment] 2020-03-10 13:38
As per my comments above, `edge` is written as synchronous Node module and will not support async calls, in order to fix it it would have to be rewritten as asynchronous module. This problem is unlikely to be resolved in `edge` in any foreseeable future.

**Closed** 2020-12-29 20:17 UTC
