### ISSUE TITLE
Issue on refreshing the window

### ISSUE THREAD

**Issue by pabloui** [agracio/electron-edge-js#132] opened 2022-04-01 15:55 UTC
Structure of application:
Window opens a specific URL like http://localhost. 
Launcher application contains all node modules i.e. electron, electron-edge-js, etc. and renderer.js is taken from URL i.e. localhost.
All dot Net compiled Dlls are in localhost.

Issue:
Everything works fine except refresh. electron-edge-js doesn't works when the window is refreshed.

**Comment by agracio** [comment] 2024-08-22 14:31
Issue is already reported here: https://github.com/agracio/electron-edge-js/issues/89 unfortunately there is no solution even now in 2024. Will be closing this as duplicate of https://github.com/agracio/electron-edge-js/issues/89 that will be kept open.

**Closed by agracio** 2024-08-22 14:31 UTC
