### ISSUE TITLE
 Error: Call to coreclr_create_delegate() for G failed with a return code of 0x80070002.

### ISSUE THREAD

**Issue by TheUnlocked** [agracio/electron-edge-js#12] opened 2018-03-25 02:39 UTC
If I set `process.env.EDGE_USE_CORECLR = 1`, then `require('electron-edge-js')` throws the error in the title. If I don't set the environment variable, I get all of the missing assembly messages.

**Comment by TheUnlocked** [comment] 2018-03-25 22:01
More research, this error occurs only when both `EGDE_USE_CORECLR` is `1` and `EDGE_APP_ROOT` is set.

**Comment by agracio** [comment] 2018-03-26 17:21
`require` itself usually does not throw any errors, the error normally appears once you try to use the module.
What version of Electron you using? You have also commented here https://github.com/agracio/edge-js-quick-start/issues/3 so I am assuming it also happens when you run quick-start project?

**Comment by TheUnlocked** [comment] 2018-03-27 00:11
Electron: 1.8.4
Node: 8.2.1

More research:
The bug originates in lib\edge.js line 55 `require(edgeNative)`.
`edgeNative` is `WHATEVERPATH\node_modules\electron-edge-js\lib\native\win32\x64\8.2.1\edge_coreclr` (for which a `.node` file does exist).

After that, the actual error site is at module.js line 503, where `Module._extensions['.node']` is a function with zero inputs, even though it is being fed two.
The reason it has zero inputs is because `overrideAPISync` from line 163 in ELECTRON_ASAR.js is called with its `name` argument populated with `'.node'` from line 697 in the same file.

This feels like an Electron issue, so I'll try to downgrade a version and see if that works.

**Comment by agracio** [comment] 2018-03-27 10:07
The error was caused by incorrect quick-start project reference, please see https://github.com/agracio/edge-js-quick-start/issues/3. The issue is fixed on both `edge-js` and `electron-edge-js` quick-start repos

**Closed** 2020-12-29 20:14 UTC
